# Generated by Django 5.0.6 on 2024-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='M', max_length=3),
        ),
    ]
