# Generated by Django 5.0.6 on 2024-07-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
